import { MetaDataType } from './MetaDataType'

export const MetaDataTypeTitle = {
  [MetaDataType.TIMESTAMP]: 'timestamp',
  [MetaDataType.WEI]: 'wei',
  [MetaDataType.FIXED_POINT_1]: 'Fixed point 1',
  [MetaDataType.FIXED_POINT_2]: 'Fixed point 2',
  [MetaDataType.FIXED_POINT_3]: 'Fixed point 3',
  [MetaDataType.FIXED_POINT_4]: 'Fixed point 4',
  [MetaDataType.FIXED_POINT_5]: 'Fixed point 5',
  [MetaDataType.FIXED_POINT_6]: 'Fixed point 6',
  [MetaDataType.FIXED_POINT_7]: 'Fixed point 7',
  [MetaDataType.FIXED_POINT_8]: 'Fixed point 8',
  [MetaDataType.FIXED_POINT_9]: 'Fixed point 9',
  [MetaDataType.FIXED_POINT_10]: 'Fixed point 10',
  [MetaDataType.FIXED_POINT_11]: 'Fixed point 11',
  [MetaDataType.FIXED_POINT_12]: 'Fixed point 12',
  [MetaDataType.FIXED_POINT_13]: 'Fixed point 13',
  [MetaDataType.FIXED_POINT_14]: 'Fixed point 14',
  [MetaDataType.FIXED_POINT_15]: 'Fixed point 15',
  [MetaDataType.FIXED_POINT_16]: 'Fixed point 16',
  [MetaDataType.FIXED_POINT_17]: 'Fixed point 17',
  [MetaDataType.FIXED_POINT_18]: 'Fixed point 18',
  [MetaDataType.FIXED_POINT_19]: 'Fixed point 19',
  [MetaDataType.FIXED_POINT_20]: 'Fixed point 20',
  [MetaDataType.FIXED_POINT_21]: 'Fixed point 21',
  [MetaDataType.FIXED_POINT_22]: 'Fixed point 22',
  [MetaDataType.FIXED_POINT_23]: 'Fixed point 23',
  [MetaDataType.FIXED_POINT_24]: 'Fixed point 24',
  [MetaDataType.FIXED_POINT_25]: 'Fixed point 25',
  [MetaDataType.FIXED_POINT_26]: 'Fixed point 26',
  [MetaDataType.FIXED_POINT_27]: 'Fixed point 27',
  [MetaDataType.FIXED_POINT_28]: 'Fixed point 28',
  [MetaDataType.FIXED_POINT_29]: 'Fixed point 29',
  [MetaDataType.FIXED_POINT_30]: 'Fixed point 30',
  [MetaDataType.FIXED_POINT_31]: 'Fixed point 31'
}
