export const BLOCK_NUMBER = 'block.number';
export const BLOCK_DIFFICULTY = 'block.difficulty';
export const BLOCK_TIMESTAMP = 'block.timestamp';
export const BLOCK_GAS_LIMIT = 'block.gasLimit';
export const BLOCK_GAS_USED = 'block.gasUsed';
export const BLOCK_MINER = 'miner';
export const TRANSACTION_CREATES = 'transaction.creates';
export const TRANSACTION_TO = 'transaction.to';
export const TRANSACTION_DATA = 'transaction.data';
export const TRANSACTION_FROM = 'transaction.from';
export const TRANSACTION_GAS_LIMIT = 'transaction.gasLimit';
export const TRANSACTION_GAS_PRICE = 'transaction.gasPrice';
export const TRANSACTION_NONCE = 'transaction.nonce';
export const TRANSACTION_VALUE = 'transaction.value';
export const TRANSACTION_CHAIN_ID = 'transaction.chainId';
export const TRANSACTION_CONTRACT_ADDRESS = 'transaction.contractAddress';
export const TRANSACTION_CUMULATIVE_GAS_USED = 'transaction.cumulativeGasUsed';
export const TRANSACTION_GAS_USED = 'transaction.gasUsed';
export const LOG_ADDRESS = 'log.address'; // originator address
export const LOG_TOPIC_0 = 'log.topic[0]'; // eventSignature(x, y, z)
export const LOG_TOPIC_1 = 'log.topic[1]';
export const LOG_TOPIC_2 = 'log.topic[2]';
export const LOG_TOPIC_3 = 'log.topic[3]';
export const LOG_DATA = 'log.data';
